- name: variables to print
  hosts: web
  vars: #play level variables ,all tasks access this play level variables
    COURSE: "DevOps with AWS"
    DURATION: "12Hrs"
    TRAINER: "Sivakumar Reddy"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi , I am learning {{COURSE}} , Duration is: {{DURATION}}, Trainer: {{TRAINER}}"

  - name: print the information again
    vars: #task level variables ,only specific task can access this variables
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi , I am learning {{COURSE}} , Duration is: {{DURATION}}, Trainer: {{TRAINER}}"

  - name: print the information again and again
    ansible.builtin.debug:
      msg: "Hi , I am learning {{COURSE}} , Duration is: {{DURATION}}, Trainer: {{TRAINER}}"