- name: variables to print
  hosts: web
  vars_prompt:
  - name: NAME
    prompt: Please enter the NAME 
  vars_files:
  - vars.yaml
  vars: 
    NAME: "from play level"
  tasks:
  - name: print the information
    vars: 
      NAME: "from task level"
    ansible.builtin.debug:
       msg: "Hello {{NAME}}"