- name: demo on filters/function
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }} "
  - name: convert to uppercase
    vars:
      greeting: "Hello Ramesh" 
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"
  - name: convert to lowercase
    vars:
      greeting: "HELLO Ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | lower}}"

  - name: print the unique value
    vars:
      numbers: [1,2,3,4,3,2,5,6]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

  - name: get the min and max value
    vars:
      numbers: [1,2,3,4,5,6]
    ansible.builtin.debug:
      msg: "min: {{numbers | min}}, max:{{numbers | max}}"
  - name: convert to map to list
    vars:
      course:
        name: "Devops with AWS"
        duration: 120
        trainer: "Sivakumar reddy"
    ansible.builtin.debug:
      msg: "{{course | dict2items}}"
  - name: convert to list to map
    vars:
      course:
        - {"key":"name","value":"Devops with AWS"}
        - {"key":"duration","value": 120hrs}
        - {"key":"trainer","value": "sivakumar reddy"}
    ansible.builtin.debug:
      msg: "{{course | items2dict}}"

  - name: check ip address
    vars:
      myip: "192.168.1.1"
    ansible.builtin.debug:
      msg: "{{myip | ansible.utils.ipv4}}"