- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.command: ls -ltr | /tmp/output.txt #command is useful for simple commands and not to redirections and pipes 